# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 07:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='\u8bf7\u8f93\u5165\u4e00\u4e2a\u5408\u6cd5\u7684\u7535\u8bdd\u53f7\u7801', regex='^\\d{11}$')])),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message='\u8bf7\u8f93\u5165\u4e00\u4e2a\u5408\u6cd5\u7684\u90ae\u4ef6\u5730\u5740')])),
            ],
        ),
    ]
